### PR TITLE
Inverted relation pages (Getting rid of o folder)

### PR DESCRIPTION
**Pull request by mushishi78**
Even if you're not planning to keep the "o" folder in the theme repository, having a pre-compile stage is still going to be a pain, especially if you want other people to contribute to your site. Here's some liquid code that'll allow you to invert the relations without pre-compiling.

### CODE REVIEW

**Comment by geraldb** [comment]
Good points. I will keep the "pre-compile" as it resolve the shortcuts (e.g. github+branch to download_url etc.) too (and some more) and it keeps the templates simpler.  I will definitely remove the o/ folder from the /themes repo that just was confusing. Sorry. Thanks for the great liquid examples. Cheers. 
 PS: Just so it makes more sense - the "pre-compile" will also pull-in more data using the GitHub API (that's the plan) e.g. number of stars, forks, last-updated for each theme etc., thus, sorry, the "pre-compile" will stay but the /o folder (in the /themes repo) will get nuked.

**Comment by mushishi78** [comment]
Well, it's your project so go with whatever you're comfortable with, though I don't see how creating a download_url would be difficult to do with liquid.

If you are going to keep the pre-compilation, may I suggest that instead of having the `themes` as a submodule, move it out, and then, when you update it, compile directly into the `_data` folder of this project and push up the changes here. That way, there's no mysteriously named "o" folder, `site.data.themes.o.themes` becomes `site.data.themes` and when someone tries to clone this project they'll get the data without having to clone the submodule or understand your confusing setup.

**Comment by mushishi78** [comment]
You should really being pulling the GitHub API data dynamically with javascript as otherwise it'll just go stale in between re-compiles.

I took the liberty of abstracting out the liquid logic into an include file for re-usability. This way the template is still relatively clean. You still don't have to go with this solution, but check how it looks now just in case it changes your mind. I'm going to open source it anyway so it's not sweat of my back.

**Comment by geraldb** [comment]
Thanks for all your efforts and great comments and suggestions. By the way - great to see the [jekyll-invert](https://github.com/mushishi78/jekyll-invert) repo (A liquid include file for Jekyll that inverts relations.) live for others to re(use) and share. Keep it up.  
PS: I was thinking through something similar but the submodule is still required for the thumbnails/screenshots (even though the themes.yml might not longer be needed to get pulled in).  Sorry - there no perfect world. Again thanks for trying. Have a great weekend.

**Comment by geraldb** [comment]
Just on more comment:

> You should really being pulling the GitHub API data dynamically with javascript 
> as otherwise it'll just go stale in between re-compiles.

The idea is to keep a history of the stars, forks (e.g. weekyl snapshots), etc in the repo itself - so I can add trending themes (e.g new stars for last week, last month etc.) and so on. Again thanks for all your ideas. Cheers.

**Comment by mushishi78** [comment]
You can get the time the stars were created by through the GitHub API: [ Starring - Alternative Response with Star Creation Timestamps](https://developer.github.com/v3/activity/starring/#alternative-response-with-star-creation-timestamps). So javascript would be more accurate, save you from having to store star history in the repository and from having a background task doing once a week compiles.

**Comment by mushishi78** [comment]
Following a [conversation on Jekyll's talk forum](https://talk.jekyllrb.com/t/jekyll-invert-a-small-liquid-include-file-for-inverting-relations/1151) it became apparent that the authors case could be achieved with `group_by` filter. I decided to change my solution to exclusively deal with the tags case, and so I rebranded it as [Jekyll Group-By-Array](https://github.com/mushishi78/jekyll-group-by-array).

I've updated this PR accordingly. Hopefully, the changes are less intimidating now with the clearer naming.

**Comment by geraldb** [comment]
Thanks for all your efforts and updates. Cheers.

**Comment by geraldb** [comment]
I've updated the /themes repo. There's no more o/ (output) folder. The o/ folder lives on here. Sorry. Thanks for your example. Cheers.

**Pull request closed without merging**
